spring.application.name=SmartWallet

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smartwallet}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
twelvedata.api.key=${TWELVE_DATA_API_KEY}
twelvedata.api.base-url=https://api.twelvedata.com